// DO NOT EDIT, generated by scripts/icon.js
export const icons = {
  mermaid:
    '<svg width="1em" height="1em" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="#fff" fill-opacity=".01" d="M0 0h48v48H0z"/><path stroke="currentColor" stroke-width="4" stroke-linejoin="round" d="M17 6h14v9H17zM6 33h14v9H6zM28 33h14v9H28z"/><path d="M24 16v8M13 33v-9h22v9" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>',
}
