// DO NOT EDIT, generated by scripts/icon.js
export const icons = {
  mermaid:
    '<svg width="1em" height="1em" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8 28a4 4 0 100-8 4 4 0 000 8zM42 8a2 2 0 100-4 2 2 0 000 4zM42 26a2 2 0 100-4 2 2 0 000 4zM42 44a2 2 0 100-4 2 2 0 000 4z" stroke="currentColor" stroke-width="4" stroke-linejoin="round"/><path d="M32 6H20v36h12M12 24h20" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>',
};
