# https://docs.netlify.com/configure-builds/file-based-configuration/#configuration-details
# https://answers.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759
[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[build]
  publish = "packages/playground/dist"
  command = "npm install -g pnpm && pnpm install && npx norm build --filter playground"
