import * as iconPark from '@icon-park/svg'

export const icons = {
  heading: iconPark.H({}),
  h1: iconPark.H1({}),
  h2: iconPark.H2({}),
  h3: iconPark.H3({}),
  h4: iconPark.LevelFourTitle({}),
  h5: iconPark.LevelFiveTitle({}),
  h6: iconPark.LevelSixTitle({}),
  bold: iconPark.TextBold({}),
  italic: iconPark.TextItalic({}),
  quote: iconPark.Quote({}),
  link: iconPark.LinkOne({}),
  image: iconPark.Pic({}),
  code: iconPark.Code({}),
  codeBlock: iconPark.CodeBrackets({}),
  ol: iconPark.OrderedList({}),
  ul: iconPark.ListTwo({}),
  hr: iconPark.DividingLine({}),
  source: iconPark.GithubOne({}),
  fullscreenOn: iconPark.FullScreen({}),
  fullscreenOff: iconPark.OffScreen({}),
  help: iconPark.Helpcenter({}),
  toc: iconPark.AlignTextLeftOne({}),
  close: iconPark.Close({}),
  left: iconPark.LeftExpand({}),
  right: iconPark.RightExpand({}),
  more: iconPark.More({}),
  keyboard: iconPark.EnterTheKeyboard({}),
}
