// DO NOT EDIT, generated by scripts/icon.js
export const icons = {
  strikethrough:
    '<svg width="1em" height="1em" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 24h38M24 24c16 6 10 20 0 20s-12-8-12-8M36 12s-3-8-12-8-12.564 7.6-8.39 14" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 36s4 8 12 8 12.564-7.6 8.39-14" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  task:
    '<svg width="1em" height="1em" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#icon-5fdf7595097271bd)" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"><path d="M42 20v19a3 3 0 01-3 3H9a3 3 0 01-3-3V9a3 3 0 013-3h21"/><path d="M16 20l10 8L41 7"/></g><defs><clipPath id="icon-5fdf7595097271bd"><path fill="currentColor" d="M0 0h48v48H0z"/></clipPath></defs></svg>',
  table:
    '<svg width="1em" height="1em" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M40.15 5H7.85A2.85 2.85 0 005 7.85v32.3A2.85 2.85 0 007.85 43h32.3A2.85 2.85 0 0043 40.15V7.85A2.85 2.85 0 0040.15 5z" stroke="currentColor" stroke-width="4"/><path d="M17 5v38M31 5v38M5 17h38M5 31h38" stroke="currentColor" stroke-width="4" stroke-linecap="round"/></svg>',
};
