// @ts-check
import fs from 'fs-extra';
import { execSync } from 'child_process';
import Svgo from 'svgo';
import * as icons from '@icon-park/svg';

const svgo = new Svgo();

const meta = {
  bytemd: {
    heading: () => `<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3 1V14.33" stroke="#333333" stroke-width="1.33" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12.9971 1V14.33" stroke="#333333" stroke-width="1.33" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M3 7.66498H12.9975" stroke="#333333" stroke-width="1.33" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`,
    bold: icons.TextBold,
    italic: icons.TextItalic,
    quote: icons.Quote,
    link: icons.LinkOne,
    code: icons.Code,
    codeBlock: icons.CodeBrackets,
    ol: icons.OrderedList,
    ul: icons.ListTwo,
    hr: icons.DividingLine,
    info: icons.Info,
    fullscreenOn: icons.FullScreen,
    fullscreenOff: icons.OffScreen,
  },
  'plugin-gfm': {
    strikethrough: icons.Strikethrough,
    task: icons.CheckCorrect,
    table: icons.InsertTable,
  },
  'plugin-import-image': {
    image: icons.Pic,
  },
  'plugin-math': {
    math: icons.Dollar,
    mathBlock: icons.Formula,
  },
  'plugin-math-ssr': {
    math: icons.Dollar,
    mathBlock: icons.Formula,
  },
  'plugin-mermaid': {
    mermaid: icons.MindMapping,
  },
};

(async () => {
  for (let [p, mapper] of Object.entries(meta)) {
    let obj = {};
    for (let [key, factory] of Object.entries(mapper)) {
      const svg = await svgo.optimize(factory({}));
      obj[key] = svg.data;
    }

    fs.writeFileSync(
      `./packages/${p}/src/icons.ts`,
      `// DO NOT EDIT, generated by scripts/icon.js
      export const icons=${JSON.stringify(obj)}`
    );
  }

  execSync('npx prettier --write packages/**/*.ts');
})();
