# https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues
# https://github.com/actions/stale

name: close inactive issues
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          exempt-issue-labels: help wanted
          exempt-all-assignees: true
          stale-issue-message: 'This issue is stale because it has been open for 60 days with no activity.'
          close-issue-message: 'This issue was closed because it has been inactive for 7 days since being marked as stale.'
          days-before-pr-stale: -1
          days-before-pr-close: -1
